name: pull-request-dev

on:
  pull_request:
    branches:
      - dev
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        timeout-minute: 60
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          path: node_modules
        run: npm ci
      
      - name: Test
        run: npm eslint && npm test
      
      - name: Build
        run: npm build
